# -*- coding: utf-8 -*-
"""PeerToPeerFileSharing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/152lB74LSSpLnIal0FQ0ni2CTc99VtIm9
"""

import matplotlib.pyplot as plt
import numpy as np

numberOfPeers = [3, 4, 5, 6, 7, 8, 9, 10]
retrieveAvgTimeSeq = [0.10253333333333334, 0.067925, 0.057408, 0.0439, 0.035289795918367346, 0.028259375, 0.025614814814814816, 0.019128]
retrieveAvgTimeParallel = [0.8332, 0.9104, 1.01088, 1.1515666666666666, 1.1839428571428572, 1.540525, 1.5356666666666667, 1.74368]

plt.xlabel('Number of Peers', fontweight ='bold', fontsize = 15)
plt.ylabel('Retrieval Execution Time', fontweight ='bold', fontsize = 15)

barWidth = 0.25
plt.bar(numberOfPeers, retrieveAvgTimeSeq, color ='r', width = barWidth,
        edgecolor ='grey', label ='RetrieveAvgTimeSeq')
plt.bar([x + 0.25 for x in numberOfPeers], retrieveAvgTimeParallel, color ='g', width = barWidth,
        edgecolor ='grey', label ='RetrieveAvgTimeParallel')

plt.plot()
plt.savefig('RetrievalAvgTimeSeqVsParallel.png')

numberOfPeers = [3, 4, 5, 6, 7, 8, 9, 10]
searchAvgTimeSeq = [0.09786666666666667, 0.0846375, 0.068376, 0.058638888888888886, 0.047146938775510204, 0.0453125, 0.04373827160493827, 0.036066]
searchAvgTimeParallel = [1.0554666666666668, 1.5511, 2.00424, 2.9821333333333335, 3.8080285714285713, 4.22525, 5.188422222222222, 5.69448]

plt.xlabel('Number of Peers', fontweight ='bold', fontsize = 15)
plt.ylabel('Search Execution Time', fontweight ='bold', fontsize = 15)

barWidth = 0.25
plt.bar(numberOfPeers, searchAvgTimeSeq, color ='r', width = barWidth,
        edgecolor ='grey', label ='SearchAvgTimeSeq')
plt.bar([x + 0.25 for x in numberOfPeers], searchAvgTimeParallel, color ='g', width = barWidth,
        edgecolor ='grey', label ='SearchAvgTimeParallel')

plt.plot()
plt.savefig('SearchAvgTimeSeqVsParallel.png')